### ISSUE TITLE
Set Location & ºF to ºC

### ISSUE THREAD

**Issue by AlienHeads** [timleland/WeatherCE#1]
Not really an issue more of a request. The location option only gives a choice of USA zip codes, i live outside America in the UK so a place name option or postcode option would be ideal. Also an option to change from ºF to ºC would be good too.

 The best weather extension i have found in the chrome store keep up the good work.

**Comment by timleland** [comment]
Glad you like it @AlienHeads. I just pushed out 2 updates. You can now set celsius or fahrenheit. You can also set any location based on address or zipcode. Let me know if you run into any issues.

**Comment by AlienHeads** [comment]
That's superb everything seems to work fine :+1:
