### ISSUE TITLE
Add option to display animated radar

### ISSUE THREAD

**Issue by Two-Tone** [timleland/WeatherCE#2]
Overall I _really_ like the look and feel of your extension, but the lack of any form of radar is a huge negative, imo. As a result I'm am currently using the far less polished "Forecast Fox (Fixed Version)".  If you ever add radar support, I'll gladly switch.

For where to put it, my suggestion would be to have an arrow right below the weekly forecast that the user can click to pull up a radar that fills the popup "window". It'd be a great size for the radar and it'd be MUCH bigger than the tiny one in Forecast Fox.

**Comment by timleland** [comment]
Thanks for the feedback! I'm glad you like the look and feel. Currently there is a pop out radar if you click on the globe icon.

![1](https://cloud.githubusercontent.com/assets/1711910/17457054/c452ff78-5bb9-11e6-99dc-b0b9cbc72e68.png)

**Comment by Two-Tone** [comment]
Never noticed that (I don't think that using a global as a symbol for radar is intuitive), although I've gotta say that it's rather annoying that it creates an actual pop-up window and that it repeats so much of the info that is already presented in the initial widget.

I still feel that a radar that is embedded in the widget would be better, but I also know that this is no easy suggestion.  

Unrelated question, but is it me or does the app only update the main weather info on click of the button?

**Comment by timleland** [comment]
The temperature badge updates every 30 minutes.  Thanks for the suggestions!

**Comment by Two-Tone** [comment]
> The temperature badge updates every 30 minutes

That's not what I was talking about. I was talking about the popup widget.
